version: '3'

vars:
  CLUSTER_NAME: 
    sh: basename "$PWD"

includes:
  storage: modules/storage/Taskfile.yaml
  networking: modules/networking/Taskfile.yaml
  apps: modules/apps/Taskfile.yaml
  auth: modules/auth/Taskfile.yaml
  dashboards: modules/dashboards/Taskfile.yaml
  gitops: modules/gitops/Taskfile.yaml
  provisioning: modules/provisioning/Taskfile.yaml
  security: modules/security/Taskfile.yaml
  001-scenarios: modules/scenarios.yaml

tasks:
  default: scripts/selectTask.sh
  001-clean: 
  - task: provisioning:k3d:delete

  update:
  - sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

  commit:
  - git add .
  - git commit -m "fast"
  - git push origin min




