version: 3

tasks:
  deploy:
    cmds:
    - >
      helm upgrade --install traefik traefik/traefik
      -f values/custom.yaml
      -n traefik
      --create-namespace
    - kubectl rollout status -n traefik deployment/traefik --timeout 1m
    status:
    - helm ls -n traefik | grep traefik