apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# bases:
# - ../../base
# patchesStrategicMerge:
# - hpa.yaml
# patchesJson6902:
#   - target:
#       version: v1
#       kind: DeploymentConfig
#       name: deepfence-console.yaml
#     path: kustomize-patch.yaml
resources:
- all.yaml
patches:
  - path: kustomize-patch-affinity.yaml
    target:
      kind: Deployment
      name: ".*"