version: 3 

tasks:
  helm:add-repo:
    cmds:
    - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    status:
    - helm repo list | grep ingress-nginx
  
  deploy:
    deps:
    - helm:add-repo
    cmds:
    - |
      helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
      -n ingress-nginx --create-namespace -f values/custom.yaml
    status:
    - helm -n ingress-nginx ls | grep ingress-nginx