apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o snoopforms --volumes emptyDir
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: snoopforms
  name: snoopforms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: snoopforms
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o snoopforms --volumes emptyDir
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: snoopforms
    spec:
      containers:
        - args:
            - sh
            - -c
            - yarn prisma migrate deploy && yarn start
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/snoopforms?schema=public
            - name: EMAIL_VERIFICATION_DISABLED
              value: "1"
            - name: NEXTAUTH_SECRET
              value: RANDOM_STRING
            - name: NEXTAUTH_URL
              value: http://localhost:3000
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: PASSWORD_RESET_DISABLED
              value: "1"
          image: ghcr.io/snoopforms/snoopforms:latest
          name: snoopforms
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
