apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o snoopforms --volumes emptyDir
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: snoopforms
  name: snoopforms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: snoopforms
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o snoopforms --volumes emptyDir
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: snoopforms
    spec:
      containers:
        - args:
            - sh
            - -c
            - yarn prisma migrate deploy && yarn start
          image: snoopforms
          name: snoopforms
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
