apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: HostRegexp(`traefik.{suffix:.*}`)
    kind: Rule
    services:   
    - kind: TraefikService 
      name: api@internal