version: 3

tasks:
  deploy: kustomize build "github.com/rancher/local-path-provisioner/deploy?ref=v0.0.22" | kubectl apply -f -
  set-as-default-storage-class:
    cmds:
    - kubectl annotate --overwrite storageclass local-path storageclass.kubernetes.io/is-default-class=true