https:
  # -- Enable the HTTPS endpoint.
  enabled: false
grpc:
  # -- Enable the gRPC endpoint.
  # Read more in the [documentation](https://dexidp.io/docs/api/).
  enabled: false

# -- Application configuration.
# See the [official documentation](https://dexidp.io/docs/).
config:
  # Set it to a valid URL
  issuer: https://dex.192.168.56.103.nip.io

  storage:
    type: kubernetes
    config:
      inCluster: true

  web:
    http: 0.0.0.0:5556
    # tlsCert: /etc/dex/tls/tls.crt
    # tlsKey: /etc/dex/tls/tls.key

  connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: $GITHUB_CLIENT_ID
      clientSecret: $GITHUB_CLIENT_SECRET
      redirectURI: https://dex.192.168.56.103.nip.io/callback
      # orgs: 
      # - name: kubernetes
      loadAllGroups: true
      useLoginAsID: true

  # Configuration for dex appearance
  # frontend:
  #   issuer: dex
  #   logoURL: theme/logo.png
  #   dir: web/
  #   theme: light

  oauth2:
    skipApprovalScreen: true
    alwaysShowLoginScreen: false

  staticClients:
  - id: kubernetes-local
    redirectURIs:
      - http://localhost:8000
      - http://localhost:18000
      - https://dex-k8s.127.0.0.1.nip.io/callback/kubernetes-local
    name: 'Kubernetes Local'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0

  # Enable at least one connector
  # See https://dexidp.io/docs/connectors/ for more options
  # enablePasswordDB: true
  # staticPasswords:
  #   - email: "admin@example.com"
  #     # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
  #     hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  #     username: "admin"
  #     userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
  
volumes:
  - name: tls
    secret:
      secretName: dex.tls
volumeMounts:
  - name: tls
    mountPath: /etc/dex/tls
envFrom:
- secretRef:
    name: github-client

ingress:
  enabled: true
  hosts:
    - host: dex.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: dex.192.168.56.103.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - secretName: dex.tls
    hosts:
    - dex.127.0.0.1.nip.io
    - dex.192.168.56.103.nip.io

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


