
apiVersion: k3d.io/v1alpha4
kind: Simple
servers: 1 
agents: 3
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
    - arg: --disable=traefik
      nodeFilters:
      - server:0



