{{ if .Values.traefik }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1" # default 0, lower priority is installed first
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: '10.x.x'
    chart: traefik
    helm:
      values: | 
        {{ .Files.Get "values/traefik.yaml" | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
{{ end }}