apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: concierge
  contents:
  - path: deploy/concierge
    git:
      url: https://github.com/vmware-tanzu/pinniped
      ref: origin/main #v0.19.0
    newRootPath: .