apiVersion: v1
kind: Service
metadata:
  labels:
    # consul.hashicorp.com/service-ignore: "true" # <- this doesnt work
  name: hostname
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: hostname
  sessionAffinity: None
  type: ClusterIP